### ISSUE TITLE
Invalid SOAP request when sending sms

### ISSUE THREAD

**Issue by damienadermann** [messagemedia/messagemedia-ruby#8]
Using the examples on the readme I'm getting the following errors ```Savon::SOAPFault: (SOAP-ENV:Client) The request is either not well-formed or is not valid against the relevant schema.
from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!' ```

E.g. Single message example
```ruby
[30] pry(main)> Messagemedia::SOAP::Client.new("MYUSER", "XXXXXXX").send_message("0444444444", "test", "abc123")

Savon::SOAPFault: (SOAP-ENV:Client) The request is either not well-formed or is not valid against the relevant schema.
from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
```

E.g. Multiple message example
```ruby
[15] pry(main)> client = Messagemedia::SOAP::Client.new("MYUSER", "XXXX")
[16] pry(main)> message1 = Messagemedia::SOAP::Message.new
=> #<Messagemedia::SOAP::Message:0x007fdefa97b838
 @delivery_report=true,
 @format="SMS",
 @recipients=[],
 @sequence_number=0,
 @validity_period=1>
[17] pry(main)> message1.content = "Content of Message"
=> "Content of Message"
[18] pry(main)> message1.delivery_report = true
=> true
[19] pry(main)> message1.origin = "My Company"
=> "My Company"
[20] pry(main)> message1.add_recipient('abc123', '0444444444')
=> [#<Messagemedia::SOAP::Recipient:0x007fdef158de78
  @destination_number="0432218897",
  @message_id="abc123">]
[21] pry(main)> client.send_messages([message1])
Savon::SOAPFault: (SOAP-ENV:Client) The request is either not well-formed or is not valid against the relevant schema.
from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
```

**Comment by pcolby** [comment]
> [20] pry(main)> message1.add_recipient('abc123', '0444444444')

As per the XSD (ultimately resolved in [CommonTypes.xsd](http://xml.m4u.com.au/2009/CommonTypes.xsd)), the recipient ID (ie `abc123`), if present, must be `xsd:unsignedInt`.

Can you please try again using an unsigned integer ID instead of `abc123`?

Looks like we need some validation in the `Messagemedia::SOAP::Message::add_recipient` method to catch this earlier.

(I'd also like to see the `message_id` property renamed to `recipient_id` - the former refers to an internal implementation, whereas the latter matches the SOAP/XML schema).

**Comment by damienadermann** [comment]
@pcolby That worked. Thankyou.

**Comment by shawr** [comment]
@pcolby do you think we should do some extra validation on add_recipient?

**Comment by pcolby** [comment]
@shawr, yeah I think so.  Not sure about the priority.

At the very least, it would be nice if the code comment on that function mentioned the unsigned-int requirement.

Cheers.
